// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';


export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

export const REQUEST_UPDATEPASSWORD = 'REQUEST_UPDATEPASSWORD';
export const SUCCESS_UPDATEPASSWORD = 'SUCCESS_UPDATEPASSWORD';

export const REQUEST_UPDATEUSER = 'REQUEST_UPDATEUSER';
export const SUCCESS_UPDATEUSER = 'SUCCESS_UPDATEUSER';
export const REQUEST_UPDATEUSERS = 'REQUEST_UPDATEUSERS';
export const SUCCESS_UPDATEUSERS = 'SUCCESS_UPDATEUSERS';

export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const SUCCESS_DELETE_USER = 'SUCCESS_DELETE_USER';

export const REQUEST_SAVE_USER = 'REQUEST_SAVE_USER';
export const SUCCESS_SAVE_USER = 'SUCCESS_SAVE_USER';

export const REQUEST_RESETPASSWORD = 'REQUEST_RESETPASSWORD';
export const SUCCESS_RESETPASSWORD = 'SUCCESS_RESETPASSWORD';


export const REQUEST_SEARCHPOSTAL = 'REQUEST_SEARCHPOSTAL';
export const SUCCESS_SEARCHPOSTAL = 'SUCCESS_SEARCHPOSTAL';


export const REQUEST_GET_BOOKINGFILTERS = 'REQUEST_GET_BOOKINGFILTERS';
export const SUCCESS_GET_BOOKINGFILTERS = 'SUCCESS_GET_BOOKINGFILTERS';


export const REQUEST_GET_SELECTED = 'REQUEST_GET_SELECTED';
export const SUCCESS_GET_SELECTED = 'SUCCESS_GET_SELECTED';





export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

export const ON_HIDE_MODAL = 'ON_HIDE_MODAL';
export const ON_SHOW_MODAL = 'ON_SHOW_MODAL';

export const REQUEST_GET_BOOKING = 'REQUEST_GET_BOOKING';
export const SUCCESS_GET_BOOKING = 'SUCCESS_GET_BOOKING';




export const REQUEST_UPDATEBULKBOOKING = 'REQUEST_UPDATEBULKBOOKING';
export const SUCCESS_UPDATEBULKBOOKING = 'SUCCESS_UPDATEBULKBOOKING';

export const REQUEST_UPDATEBOOKING = 'REQUEST_UPDATEBOOKING';
export const SUCCESS_UPDATEBOOKING = 'SUCCESS_UPDATEBOOKING';

export const REQUEST_GET_PARCEL = 'REQUEST_GET_PARCEL';
export const SUCCESS_GET_PARCEL = 'SUCCESS_GET_PARCEL';


export const REQUEST_ADDMOREPARCEL = 'REQUEST_ADDMOREPARCEL';
export const SUCCESS_ADDMOREPARCEL = 'SUCCESS_ADDMOREPARCEL';

export const REQUEST_UPDATECOSTBOOKING = 'REQUEST_UPDATECOSTBOOKING';
export const SUCCESS_UPDATECOSTBOOKING = 'SUCCESS_UPDATECOSTBOOKING';

export const REQUEST_CREATEPARCELITEM = 'REQUEST_CREATEPARCELITEM';
export const SUCCESS_CREATEPARCELITEM = 'SUCCESS_CREATEPARCELITEM';

export const REQUEST_CREATEBOOKING = 'REQUEST_CREATEBOOKING';
export const SUCCESS_CREATEBOOKING = 'SUCCESS_CREATEBOOKING';

export const REQUEST_UPDATEDELIVERY = 'REQUEST_UPDATEDELIVERY';
export const SUCCESS_UPDATEDELIVERY = 'SUCCESS_UPDATEDELIVERY';

export const REQUEST_CREATEBOOKINGIMPORT = 'REQUEST_CREATEBOOKINGIMPORT';
export const SUCCESS_CREATEBOOKINGIMPORT = 'SUCCESS_CREATEBOOKINGIMPORT';

export const REQUEST_CREATEBOOKINGPARCELIMPORT = 'REQUEST_CREATEBOOKINGPARCELIMPORT';
export const SUCCESS_CREATEBOOKINGPARCELIMPORT = 'SUCCESS_CREATEBOOKINGPARCELIMPORT';

export const REQUEST_CREATEBOOKINGPAYIMPORT = 'REQUEST_CREATEBOOKINGPAYIMPORT';
export const SUCCESS_CREATEBOOKINGPAYIMPORT = 'SUCCESS_CREATEBOOKINGPAYIMPORT';

export const REQUEST_CREATEBOOKINGPAYDETIMPORT = 'REQUEST_CREATEBOOKINGPAYDETIMPORT';
export const SUCCESS_CREATEBOOKINGPAYDETIMPORT = 'SUCCESS_CREATEBOOKINGPAYDETIMPORT';


export const REQUEST_GET_PAYMENTS = 'REQUEST_GET_PAYMENTS';
export const SUCCESS_GET_PAYMENTS = 'SUCCESS_GET_PAYMENTS';

export const REQUEST_GET_BOOKING_COUNT = 'REQUEST_GET_BOOKING_COUNT';
export const SUCCESS_GET_BOOKING_COUNT = 'SUCCESS_GET_BOOKING_COUNT';

export const REQUEST_GET_PAYMENTDETAILS = 'REQUEST_GET_PAYMENTDETAILS';
export const SUCCESS_GET_PAYMENTDETAILS = 'SUCCESS_GET_PAYMENTDETAILS';

export const REQUEST_GET_ALLPAYMENTDETAILS = 'REQUEST_GET_ALLPAYMENTDETAILS';
export const SUCCESS_GET_ALLPAYMENTDETAILS = 'SUCCESS_GET_ALLPAYMENTDETAILS';

export const REQUEST_CREATEPAYMENT = 'REQUEST_CREATEPAYMENT';
export const SUCCESS_CREATEPAYMENT = 'SUCCESS_CREATEPAYMENT';

export const REQUEST_UPDATEPAYMENTDETAILS = 'REQUEST_UPDATEPAYMENTDETAILS';
export const SUCCESS_UPDATEPAYMENTDETAILS = 'SUCCESS_UPDATEPAYMENTDETAILS';

export const REQUEST_UPDATEBADDEBT = 'REQUEST_UPDATEBADDEBT';
export const SUCCESS_UPDATEBADDEBT = 'SUCCESS_UPDATEBADDEBT';

export const REQUEST_UPDATEPAYGH = 'REQUEST_UPDATEPAYGH';
export const SUCCESS_UPDATEPAYGH = 'SUCCESS_UPDATEPAYGH';

export const REQUEST_SMSBAL = 'REQUEST_SMSBAL';
export const SUCCESS_SMSBAL = 'SUCCESS_SMSBAL';
 

export const REQUEST_GET_SALESLISTS = 'REQUEST_GET_SALESLISTS';
export const SUCCESS_GET_SALESLISTS = 'SUCCESS_GET_SALESLISTS';

export const REQUEST_GET_CASHTRANS = 'REQUEST_GET_CASHTRANS';
export const SUCCESS_GET_CASHTRANS = 'SUCCESS_GET_CASHTRANS';

export const REQUEST_END_DAY = 'REQUEST_END_DAY';
export const SUCCESS_END_DAY = 'SUCCESS_END_DAY';


export const REQUEST_SENDSMS = 'REQUEST_SENDSMS';
export const SUCCESS_SENDSMS = 'SUCCESS_SENDSMS';




export const REQUEST_GET_ABOUT = 'REQUEST_GET_ABOUT';
export const SUCCESS_GET_ABOUT = 'SUCCESS_GET_ABOUT';
export const REQUEST_SAVE_ABOUT = 'REQUEST_SAVE_ABOUT';
export const SUCCESS_SAVE_ABOUT = 'SUCCESS_SAVE_ABOUT';
export const REQUEST_UPDATE_ABOUT = 'REQUEST_UPDATE_ABOUT';
export const SUCCESS_UPDATE_ABOUT = 'SUCCESS_UPDATE_ABOUT';
export const REQUEST_DELETE_ABOUT = 'REQUEST_DELETE_ABOUT';
export const SUCCESS_DELETE_ABOUT = 'SUCCESS_DELETE_ABOUT';




export const REQUEST_GET_MASTHEAD = 'REQUEST_GET_MASTHEAD';
export const SUCCESS_GET_MASTHEAD = 'SUCCESS_GET_MASTHEAD';
export const REQUEST_SAVE_MASTHEAD = 'REQUEST_SAVE_MASTHEAD';
export const SUCCESS_SAVE_MASTHEAD = 'SUCCESS_SAVE_MASTHEAD';
export const REQUEST_UPDATE_MASTHEAD = 'REQUEST_UPDATE_MASTHEAD';
export const SUCCESS_UPDATE_MASTHEAD = 'SUCCESS_UPDATE_MASTHEAD';
export const REQUEST_DELETE_MASTHEAD = 'REQUEST_DELETE_MASTHEAD';
export const SUCCESS_DELETE_MASTHEAD = 'SUCCESS_DELETE_MASTHEAD';



export const REQUEST_GET_LINKGROUP = 'REQUEST_GET_LINKGROUP';
export const SUCCESS_GET_LINKGROUP = 'SUCCESS_GET_LINKGROUP';
export const REQUEST_SAVE_LINKGROUP = 'REQUEST_SAVE_LINKGROUP';
export const SUCCESS_SAVE_LINKGROUP = 'SUCCESS_SAVE_LINKGROUP';
export const REQUEST_UPDATE_LINKGROUP = 'REQUEST_UPDATE_LINKGROUP';
export const SUCCESS_UPDATE_LINKGROUP = 'SUCCESS_UPDATE_LINKGROUP';
export const REQUEST_DELETE_LINKGROUP = 'REQUEST_DELETE_LINKGROUP';
export const SUCCESS_DELETE_LINKGROUP = 'SUCCESS_DELETE_LINKGROUP';

export const REQUEST_GET_USEFULLINKS = 'REQUEST_GET_USEFULLINKS';
export const SUCCESS_GET_USEFULLINKS = 'SUCCESS_GET_USEFULLINKS';
export const REQUEST_SAVE_USEFULLINKS = 'REQUEST_SAVE_USEFULLINKS';
export const SUCCESS_SAVE_USEFULLINKS = 'SUCCESS_SAVE_USEFULLINKS';
export const REQUEST_UPDATE_USEFULLINKS = 'REQUEST_UPDATE_USEFULLINKS';
export const SUCCESS_UPDATE_USEFULLINKS = 'SUCCESS_UPDATE_USEFULLINKS';
export const REQUEST_DELETE_USEFULLINKS = 'REQUEST_DELETE_USEFULLINKS';
export const SUCCESS_DELETE_USEFULLINKS = 'SUCCESS_DELETE_USEFULLINKS';

 

export const REQUEST_GET_PUBLICATION = 'REQUEST_GET_PUBLICATION';
export const SUCCESS_GET_PUBLICATION = 'SUCCESS_GET_PUBLICATION';
export const REQUEST_SAVE_PUBLICATION = 'REQUEST_SAVE_PUBLICATION';
export const SUCCESS_SAVE_PUBLICATION = 'SUCCESS_SAVE_PUBLICATION';
export const REQUEST_UPDATE_PUBLICATION = 'REQUEST_UPDATE_PUBLICATION';
export const SUCCESS_UPDATE_PUBLICATION = 'SUCCESS_UPDATE_PUBLICATION';
export const REQUEST_DELETE_PUBLICATION = 'REQUEST_DELETE_PUBLICATION';
export const SUCCESS_DELETE_PUBLICATION = 'SUCCESS_DELETE_PUBLICATION';

export const REQUEST_GET_MEMBER = 'REQUEST_GET_MEMBER';
export const SUCCESS_GET_MEMBER = 'SUCCESS_GET_MEMBER';
export const REQUEST_SAVE_MEMBER = 'REQUEST_SAVE_MEMBER';
export const SUCCESS_SAVE_MEMBER = 'SUCCESS_SAVE_MEMBER';
export const REQUEST_UPDATE_MEMBER = 'REQUEST_UPDATE_MEMBER';
export const SUCCESS_UPDATE_MEMBER = 'SUCCESS_UPDATE_MEMBER';
export const REQUEST_DELETE_MEMBER = 'REQUEST_DELETE_MEMBER';
export const SUCCESS_DELETE_MEMBER = 'SUCCESS_DELETE_MEMBER';

export const REQUEST_GET_SIMPLECHANGE = 'REQUEST_GET_SIMPLECHANGE';
export const SUCCESS_GET_SIMPLECHANGE = 'SUCCESS_GET_SIMPLECHANGE';
export const REQUEST_SAVE_SIMPLECHANGE = 'REQUEST_SAVE_SIMPLECHANGE';
export const SUCCESS_SAVE_SIMPLECHANGE = 'SUCCESS_SAVE_SIMPLECHANGE';
export const REQUEST_UPDATE_SIMPLECHANGE = 'REQUEST_UPDATE_SIMPLECHANGE';
export const SUCCESS_UPDATE_SIMPLECHANGE = 'SUCCESS_UPDATE_SIMPLECHANGE';
export const REQUEST_DELETE_SIMPLECHANGE = 'REQUEST_DELETE_SIMPLECHANGE';
export const SUCCESS_DELETE_SIMPLECHANGE = 'SUCCESS_DELETE_SIMPLECHANGE';


export const REQUEST_GET_PRODUCT = 'REQUEST_GET_PRODUCT';
export const SUCCESS_GET_PRODUCT = 'SUCCESS_GET_PRODUCT';
export const REQUEST_SAVE_PRODUCT = 'REQUEST_SAVE_PRODUCT';
export const SUCCESS_SAVE_PRODUCT = 'SUCCESS_SAVE_PRODUCT';
export const REQUEST_SAVE_BULKPRODUCT = 'REQUEST_SAVE_BULKPRODUCT';
export const SUCCESS_SAVE_BULKPRODUCT = 'SUCCESS_SAVE_BULKPRODUCT';
export const REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT';
export const SUCCESS_UPDATE_PRODUCT = 'SUCCESS_UPDATE_PRODUCT';
export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT';
export const SUCCESS_DELETE_PRODUCT = 'SUCCESS_DELETE_PRODUCT';

export const REQUEST_GET_CUSTOMER = 'REQUEST_GET_CUSTOMER';
export const SUCCESS_GET_CUSTOMER = 'SUCCESS_GET_CUSTOMER';
export const REQUEST_SAVE_CUSTOMER = 'REQUEST_SAVE_CUSTOMER';
export const SUCCESS_SAVE_CUSTOMER = 'SUCCESS_SAVE_CUSTOMER';
export const REQUEST_UPDATE_CUSTOMER = 'REQUEST_UPDATE_CUSTOMER';
export const SUCCESS_UPDATE_CUSTOMER = 'SUCCESS_UPDATE_CUSTOMER';
export const REQUEST_DELETE_CUSTOMER = 'REQUEST_DELETE_CUSTOMER';
export const SUCCESS_DELETE_CUSTOMER = 'SUCCESS_DELETE_CUSTOMER';

export const REQUEST_GET_SUPPLIER = 'REQUEST_GET_SUPPLIER';
export const SUCCESS_GET_SUPPLIER = 'SUCCESS_GET_SUPPLIER';
export const REQUEST_SAVE_SUPPLIER = 'REQUEST_SAVE_SUPPLIER';
export const SUCCESS_SAVE_SUPPLIER = 'SUCCESS_SAVE_SUPPLIER';
export const REQUEST_UPDATE_SUPPLIER = 'REQUEST_UPDATE_SUPPLIER';
export const SUCCESS_UPDATE_SUPPLIER = 'SUCCESS_UPDATE_SUPPLIER';
export const REQUEST_DELETE_SUPPLIER = 'REQUEST_DELETE_SUPPLIER';
export const SUCCESS_DELETE_SUPPLIER = 'SUCCESS_DELETE_SUPPLIER';

export const REQUEST_GET_STOCK = 'REQUEST_GET_STOCK';
export const SUCCESS_GET_STOCK = 'SUCCESS_GET_STOCK';
export const REQUEST_SAVE_STOCK = 'REQUEST_SAVE_STOCK';
export const SUCCESS_SAVE_STOCK = 'SUCCESS_SAVE_STOCK';
export const REQUEST_UPDATE_STOCK = 'REQUEST_UPDATE_STOCK';
export const SUCCESS_UPDATE_STOCK = 'SUCCESS_UPDATE_STOCK';
export const REQUEST_DELETE_STOCK = 'REQUEST_DELETE_STOCK';
export const SUCCESS_DELETE_STOCK = 'SUCCESS_DELETE_STOCK';

export const REQUEST_GET_WAREHOUSE = 'REQUEST_GET_WAREHOUSE';
export const SUCCESS_GET_WAREHOUSE = 'SUCCESS_GET_WAREHOUSE';
export const REQUEST_SAVE_WAREHOUSE = 'REQUEST_SAVE_WAREHOUSE';
export const SUCCESS_SAVE_WAREHOUSE = 'SUCCESS_SAVE_WAREHOUSE';
export const REQUEST_UPDATE_WAREHOUSE = 'REQUEST_UPDATE_WAREHOUSE';
export const SUCCESS_UPDATE_WAREHOUSE = 'SUCCESS_UPDATE_WAREHOUSE';
export const REQUEST_DELETE_WAREHOUSE = 'REQUEST_DELETE_WAREHOUSE';
export const SUCCESS_DELETE_WAREHOUSE = 'SUCCESS_DELETE_WAREHOUSE';

export const REQUEST_GET_PROFOMA = 'REQUEST_GET_PROFOMA';
export const SUCCESS_GET_PROFOMA = 'SUCCESS_GET_PROFOMA';
export const REQUEST_SAVE_PROFOMA = 'REQUEST_SAVE_PROFOMA';
export const SUCCESS_SAVE_PROFOMA = 'SUCCESS_SAVE_PROFOMA';
export const REQUEST_UPDATE_PROFOMA = 'REQUEST_UPDATE_PROFOMA';
export const SUCCESS_UPDATE_PROFOMA = 'SUCCESS_UPDATE_PROFOMA';
export const REQUEST_DELETE_PROFOMA = 'REQUEST_DELETE_PROFOMA';
export const SUCCESS_DELETE_PROFOMA = 'SUCCESS_DELETE_PROFOMA';



export const REQUEST_SAVE_MOVEMENT = 'REQUEST_SAVE_MOVEMENT';
export const SUCCESS_SAVE_MOVEMENT = 'SUCCESS_SAVE_MOVEMENT';

export const REQUEST_SAVE_MOVEMENTAUTHORIZED = 'REQUEST_SAVE_MOVEMENTAUTHORIZED';
export const SUCCESS_SAVE_MOVEMENTAUTHORIZED = 'SUCCESS_SAVE_MOVEMENTAUTHORIZED';

export const REQUEST_GET_PENDINGMOVEMENT = 'REQUEST_GET_PENDINGMOVEMENT';
export const SUCCESS_GET_PENDINGMOVEMENT = 'SUCCESS_GET_PENDINGMOVEMENT';

export const REQUEST_GET_PENDINGSTOCKTRANSFER = 'REQUEST_GET_PENDINGSTOCKTRANSFER';
export const SUCCESS_GET_PENDINGSTOCKTRANSFER = 'SUCCESS_GET_PENDINGSTOCKTRANSFER';

export const REQUEST_GET_PENDINGMOVEMENT_SUMMARY = 'REQUEST_GET_PENDINGMOVEMENT_SUMMARY';
export const SUCCESS_GET_PENDINGMOVEMENT_SUMMARY = 'SUCCESS_GET_PENDINGMOVEMENT_SUMMARY';

export const REQUEST_GET_WAREHOUSESTOCK = 'REQUEST_GET_WAREHOUSESTOCK';
export const SUCCESS_GET_WAREHOUSESTOCK = 'SUCCESS_GET_WAREHOUSESTOCK';

export const REQUEST_GET_AVAILABLESTOCK = 'REQUEST_GET_AVAILABLESTOCK';
export const SUCCESS_GET_AVAILABLESTOCK = 'SUCCESS_GET_AVAILABLESTOCK';


export const REQUEST_GET_BRANCH = 'REQUEST_GET_BRANCH';
export const SUCCESS_GET_BRANCH = 'SUCCESS_GET_BRANCH';

export const REQUEST_SAVE_BRANCH = 'REQUEST_SAVE_BRANCH';
export const SUCCESS_SAVE_BRANCH = 'SUCCESS_SAVE_BRANCH';
export const REQUEST_UPDATE_BRANCH = 'REQUEST_UPDATE_BRANCH';
export const SUCCESS_UPDATE_BRANCH = 'SUCCESS_UPDATE_BRANCH';
export const REQUEST_DELETE_BRANCH = 'REQUEST_DELETE_BRANCH';
export const SUCCESS_DELETE_BRANCH = 'SUCCESS_DELETE_BRANCH';

export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';
export const SUCCESS_GET_USERS = 'SUCCESS_GET_USERS';

export const REQUEST_GET_STATUS = 'REQUEST_GET_STATUS';
export const SUCCESS_GET_STATUS = 'SUCCESS_GET_STATUS';


export const REQUEST_SAVE_STOCKTRANSFER = 'REQUEST_SAVE_STOCKTRANSFER';
export const SUCCESS_SAVE_STOCKTRANSFER = 'SUCCESS_SAVE_STOCKTRANSFER';
export const REQUEST_SAVE_STOCKTRANSFERAUTHORIZED = 'REQUEST_SAVE_STOCKTRANSFERAUTHORIZED';
export const SUCCESS_SAVE_STOCKTRANSFERAUTHORIZED = 'SUCCESS_SAVE_STOCKTRANSFERAUTHORIZED';
export const REQUEST_GET_PENDINGSTOCKTRANSFER_SUMMARY = 'REQUEST_GET_PENDINGSTOCKTRANSFER_SUMMARY';
export const SUCCESS_GET_PENDINGSTOCKTRANSFER_SUMMARY = 'SUCCESS_GET_PENDINGSTOCKTRANSFER_SUMMARY';


export const REQUEST_SAVE_CASHTRANS = 'REQUEST_SAVE_CASHTRANS';
export const SUCCESS_SAVE_CASHTRANS = 'SUCCESS_SAVE_CASHTRANS';

export const REQUEST_SAVE_SALES = 'REQUEST_SAVE_SALES';
export const SUCCESS_SAVE_SALES = 'SUCCESS_SAVE_SALES';

export const REQUEST_DELETE_SALES = 'REQUEST_DELETE_SALES';
export const SUCCESS_DELETE_SALES = 'SUCCESS_DELETE_SALES';

export const REQUEST_GET_SALES = 'REQUEST_GET_SALES';
export const SUCCESS_GET_SALES = 'SUCCESS_GET_SALES';

export const REQUEST_GET_EXPECTEDSALES = 'REQUEST_GET_EXPECTEDSALES';
export const SUCCESS_GET_EXPECTEDSALES = 'SUCCESS_GET_EXPECTEDSALES';

export const REQUEST_GET_SALEDETAILS = 'REQUEST_GET_SALEDETAILS';
export const SUCCESS_GET_SALEDETAILS = 'SUCCESS_GET_SALEDETAILS';


export const REQUEST_GET_MONTHSALES = 'REQUEST_GET_MONTHSALES';
export const SUCCESS_GET_MONTHSALES = 'SUCCESS_GET_MONTHSALES';

export const REQUEST_GET_BILLDUE = 'REQUEST_GET_BILLDUE';
export const SUCCESS_GET_BILLDUE = 'SUCCESS_GET_BILLDUE';
export const REQUEST_GET_TOPCUSTOMER = 'REQUEST_GET_TOPCUSTOMER';
export const SUCCESS_GET_TOPCUSTOMER = 'SUCCESS_GET_TOPCUSTOMER';



export const REQUEST_GET_LEDGERHEAD = 'REQUEST_GET_LEDGERHEAD';
export const SUCCESS_GET_LEDGERHEAD = 'SUCCESS_GET_LEDGERHEAD';

export const REQUEST_GET_LEDGER = 'REQUEST_GET_LEDGER';
export const SUCCESS_GET_LEDGER = 'SUCCESS_GET_LEDGER';
export const REQUEST_SAVE_LEDGER = 'REQUEST_SAVE_LEDGER';
export const SUCCESS_SAVE_LEDGER = 'SUCCESS_SAVE_LEDGER';
export const REQUEST_UPDATE_LEDGER = 'REQUEST_UPDATE_LEDGER';
export const SUCCESS_UPDATE_LEDGER = 'SUCCESS_UPDATE_LEDGER';
export const REQUEST_DELETE_LEDGER = 'REQUEST_DELETE_LEDGER';
export const SUCCESS_DELETE_LEDGER = 'SUCCESS_DELETE_LEDGER';



export const REQUEST_GET_PERMISSION = 'REQUEST_GET_PERMISSION';
export const SUCCESS_GET_PERMISSION = 'SUCCESS_GET_PERMISSION';

export const REQUEST_SAVE_PERMISSION = 'REQUEST_SAVE_PERMISSION';
export const SUCCESS_SAVE_PERMISSION = 'SUCCESS_SAVE_PERMISSION';
export const REQUEST_UPDATE_PERMISSION = 'REQUEST_UPDATE_PERMISSION';
export const SUCCESS_UPDATE_PERMISSION = 'SUCCESS_UPDATE_PERMISSION';
export const REQUEST_DELETE_PERMISSION = 'REQUEST_DELETE_PERMISSION';
export const SUCCESS_DELETE_PERMISSION = 'SUCCESS_DELETE_PERMISSION';

export const REQUEST_GET_ROLE = 'REQUEST_GET_ROLE';
export const SUCCESS_GET_ROLE = 'SUCCESS_GET_ROLE';


export const REQUEST_SAVE_ROLE = 'REQUEST_SAVE_ROLE';
export const SUCCESS_SAVE_ROLE = 'SUCCESS_SAVE_ROLE';
export const REQUEST_UPDATE_ROLE = 'REQUEST_UPDATE_ROLE';
export const SUCCESS_UPDATE_ROLE = 'SUCCESS_UPDATE_ROLE';
export const REQUEST_DELETE_ROLE = 'REQUEST_DELETE_ROLE';
export const SUCCESS_DELETE_ROLE = 'SUCCESS_DELETE_ROLE';


export const GHOST_TO = 'GHOST_TO'
export const GHOST_TO_SUCCESS = 'GHOST_TO_SUCCESS'

export const GET_PAYMODE = 'GET_PAYMODE'
export const SUCCESS_PAYMODE = 'SUCCESS_PAYMODE'

export const REQUEST_SAVE_PAYMODE = 'REQUEST_SAVE_PAYMODE';
export const SUCCESS_SAVE_PAYMODE = 'SUCCESS_SAVE_PAYMODE';
export const REQUEST_UPDATE_PAYMODE = 'REQUEST_UPDATE_PAYMODE';
export const SUCCESS_UPDATE_PAYMODE = 'SUCCESS_UPDATE_PAYMODE';
export const REQUEST_DELETE_PAYMODE = 'REQUEST_DELETE_PAYMODE';
export const SUCCESS_DELETE_PAYMODE = 'SUCCESS_DELETE_PAYMODE';
